# -*- coding: utf-8 -*-
"""if-else

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXPZHvR5yNC0cAoQ1yf6pMAC1bJvlyvy
"""

# Q1 Write a program that takes an integer input from the user and checks whether the number is odd or
# even.
a=int(input())
if a%2==0:
  print("even")
else:
  print("odd")

# Q2 Write a program that takes three numbers as input and prints the largest of the three.
a=int(input())
b=int(input())
c=int(input())
if a>b and a>c:
  print("a is greater")
elif b>a and b>c:
  print("b is greater")
else:
  print("c is greater")

# Q3 Write a program to check if a given year is a leap year. A leap year is divisible by 4 but not by 100
# unless it is also divisible by 400.
year=2023
if year%4==0 and year%100!=0:
  print("leap year")
elif year%100==0 and year%400==0:
  print("leap year")
else:
  print("not a leap year")

# Q4 Write a program that takes a percentage (integer) as input and prints the corresponding grade based
# on the following criteria:
# >= 90: Grade A
# >= 80: Grade B
# >= 70: Grade C
# >= 60: Grade D
# < 60: Grade F
percentage=float(input())
if percentage>=90:
  print("A")
elif percentage>=80:
  print("B")
elif percentage>=70:
  print("C")
elif percentage>=60:
  print("D")
else:
  print("F")

# Q5 Write a program that checks if a given letter is a vowel (a, e, i, o, u) or a consonant.
letter=input()
if letter =='a' or letter=='e' or letter =='i' or letter =='o' or letter =='u' or letter =='A' or letter =='E' or letter =='I'or letter =='O' or letter =='U':
  print("vowel")
else:
  print("consonent")

# Q6 Write a basic calculator program that takes two numbers and an operator (+, -, *, /) as input and
# performs the specified operation. Print the result based on the operation.
a=int(input())
b=int(input())
operator=input()
if operator=="+":
  print(a+b)
elif operator=="-":
  print(a-b)
elif operator=="*":
 print(a*b)
elif operator=="/":
 print(a/b)
else:
  print("not valid")

# Q7 Write a program that takes a number as input and checks whether it is positive, negative, or zero.
number=int(input())
if number>0:
  print("positive")
elif number<0:
  print("negative")
else:
  print("zero")

# Q8 Write a program that checks if a username and password entered by the user match the pre-set values
# username = "admin" and password = "1234". If both match, print "Login Successful", otherwise print
# "Login Failed".
username=input()
password=input()
if username=='admin' and password==1234:
  print("Login Successful")
else:
  print("Login Failed")

# Q9 Write a program that takes three sides of a triangle as input and checks if those sides form a valid
# triangle. A triangle is valid if the sum of any two sides is greater than the third side.
# Check conditions like a + b > c, b + c > a, and a + c > b.
a=int(input())
b=int(input())
c=int(input())
if a+b>c and b+c>a and a+c>b:
    print("triangle")
else:
  print("not6")

# Q10 Write a program that calculates the Body Mass Index (BMI) based on user input for weight (in
# kilograms) and height (in meters). Then categorize the BMI into:
# Underweight (BMI < 18.5)
# Normal weight (18.5 <= BMI < 24.9)
# Overweight (25 <= BMI < 29.9)
# Obesity (BMI >= 30)
weight=float(input())
height=float(input())
BMI=weight/(height**2)
print(BMI)
if BMI <18.5:
  print("Underweight")
elif BMI>=18.5 or BMI <24.9:
  print("Normal weight")
elif BMI>=25 or BMI <29.9:
  print("Overweight")
else:
  print("Obesity")

# Q11 Write a program that calculates the discount for a product based on its price:
# If price is greater than 1000, discount is 10%
# If price is between 500 and 1000, discount is 5%
# Otherwise, no discount
# Print the final price after applying the discount.
price=int(input())
if price>1000:
  print(price-price*(10/100))
elif price>500 or price<1000:
  print(price-price*(5/100))
else:
  print("no discount")

# Q12 Write a program that takes the name of a month as input and prints the number of days in that
# month. Consider leap years for February.
month=input()
if month=='January' or month=='March' or month=='May' or month=='July' or month=='August' or month=='October' or month=='December':
  print("31")
elif month=='April' or month=='June' or month=='September' or month=='November':
  print("30")
elif month=='February':
  Year=int(input())
  if (Year%4==0 and Year%100!=100) or Year%400==0:
    print("29")
  else:
    print("28")
else:
  print("Year not valid")

# Q13 Write a program that simulates a simple ATM. The user should be able to:
# Check balance
# Deposit money
# Withdraw money (ensure the balance doesn't go negative) Use an if-else structure to handle the user's
# choices.
balance=1000
choice=int(input())
if choice==1:
  print("Balance",balance)
elif choice==2:
  deposit=int(input())
  print("Deposit money",balance+deposit)
elif choice==3:
  withdraw=int(input())
  if withdraw<=balance:
   print("Withdraw money",balance-withdraw)
  else:
   print("Insufficient balance")
else:
  print("please enter the right key")

# Q14 Write a program that categorizes a given age into different groups:
# Infant (0-1 year)
# Toddler (2-4 years)
# Child (5-12 years)
# Teenager (13-19 years)
# Adult (20-59 years)
# Senior (60 years and above)
age=int(input())
if age>0 and age<1:
  print("Infant")
elif age>2 and age<4:
  print("Toddler")
elif age>5 and age<12:
  print("Child")
elif age>13 and age<19:
  print("Teenager")
elif age>20 and age<59:
  print("Adult")
else:
  print("Senior")

# Q15 Write a program that takes an integer (1-7) as input and prints the corresponding day of the week (1
# for Monday, 2 for Tuesday, etc.).
integer=int(input())
if integer==1:
  print("Monday")
elif integer==2:
  print("Tuesday")
elif integer==3:
  print("Wednesday")
elif integer==4:
  print("Thursday")
elif integer==5:
  print("Friday")
elif integer==6:
  print("Saturday")
elif integer==7:
  print("Sunday")
else:
  print("Not available")